# Toolchain for cross-building Win64 binaries on Linux and running them with Wine.
#
# Override GMPFRXX_MKII_MINGW_DEPS_ROOT when GMP/MPFR/MPC are installed
# somewhere other than /home/docker/mplapack/external/i.

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(GMPFRXX_MKII_MINGW_TRIPLE "x86_64-w64-mingw32" CACHE STRING
    "MinGW-w64 target triple")
set(GMPFRXX_MKII_MINGW_DEPS_ROOT "/home/docker/mplapack/external/i" CACHE PATH
    "Root containing GMP, MPFR, and MPC MinGW installations")
set(GMPFRXX_MKII_DEPS_HOST "${GMPFRXX_MKII_MINGW_TRIPLE}" CACHE STRING
    "Autotools --host value for auto-built MinGW dependencies")

set(CMAKE_C_COMPILER "${GMPFRXX_MKII_MINGW_TRIPLE}-gcc" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${GMPFRXX_MKII_MINGW_TRIPLE}-g++" CACHE FILEPATH "")
set(CMAKE_RC_COMPILER "${GMPFRXX_MKII_MINGW_TRIPLE}-windres" CACHE FILEPATH "")

find_program(GMPFRXX_MKII_WINE_PROGRAM wine)
if(NOT GMPFRXX_MKII_WINE_PROGRAM)
    message(FATAL_ERROR "wine is required to run MinGW cross-built tests")
endif()
set(CMAKE_CROSSCOMPILING_EMULATOR "${GMPFRXX_MKII_WINE_PROGRAM}" CACHE FILEPATH
    "Emulator used by try_run() and CTest for MinGW executables")

set(GMPFRXX_MKII_MINGW_GMP_PREFIX "${GMPFRXX_MKII_MINGW_DEPS_ROOT}/GMP" CACHE PATH
    "MinGW GMP prefix")
set(GMPFRXX_MKII_MINGW_MPFR_PREFIX "${GMPFRXX_MKII_MINGW_DEPS_ROOT}/MPFR" CACHE PATH
    "MinGW MPFR prefix")
set(GMPFRXX_MKII_MINGW_MPC_PREFIX "${GMPFRXX_MKII_MINGW_DEPS_ROOT}/MPC" CACHE PATH
    "MinGW MPC prefix")

if(EXISTS "${GMPFRXX_MKII_MINGW_GMP_PREFIX}/include/gmp.h" AND
   EXISTS "${GMPFRXX_MKII_MINGW_GMP_PREFIX}/lib/libgmp.dll.a")
    set(GMP_INCLUDE_DIR "${GMPFRXX_MKII_MINGW_GMP_PREFIX}/include" CACHE PATH "")
    set(GMP_LIBRARY "${GMPFRXX_MKII_MINGW_GMP_PREFIX}/lib/libgmp.dll.a" CACHE FILEPATH "")
endif()
if(EXISTS "${GMPFRXX_MKII_MINGW_MPFR_PREFIX}/include/mpfr.h" AND
   EXISTS "${GMPFRXX_MKII_MINGW_MPFR_PREFIX}/lib/libmpfr.dll.a")
    set(MPFR_INCLUDE_DIR "${GMPFRXX_MKII_MINGW_MPFR_PREFIX}/include" CACHE PATH "")
    set(MPFR_LIBRARY "${GMPFRXX_MKII_MINGW_MPFR_PREFIX}/lib/libmpfr.dll.a" CACHE FILEPATH "")
endif()
if(EXISTS "${GMPFRXX_MKII_MINGW_MPC_PREFIX}/include/mpc.h" AND
   EXISTS "${GMPFRXX_MKII_MINGW_MPC_PREFIX}/lib/libmpc.dll.a")
    set(MPC_INCLUDE_DIR "${GMPFRXX_MKII_MINGW_MPC_PREFIX}/include" CACHE PATH "")
    set(MPC_LIBRARY "${GMPFRXX_MKII_MINGW_MPC_PREFIX}/lib/libmpc.dll.a" CACHE FILEPATH "")
endif()

set(CMAKE_FIND_ROOT_PATH
    "/usr/${GMPFRXX_MKII_MINGW_TRIPLE}"
    "${GMPFRXX_MKII_MINGW_GMP_PREFIX}"
    "${GMPFRXX_MKII_MINGW_MPFR_PREFIX}"
    "${GMPFRXX_MKII_MINGW_MPC_PREFIX}"
    CACHE STRING "MinGW find roots")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Keep the C++ runtime out of WINEPATH. GMP/MPFR/MPC still use their DLLs.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libgcc -static-libstdc++")
